using UnityEngine;
using Cinemachine;

public class RotacionCamara : MonoBehaviour
{
    public Transform personaje;
    public float sensibilidadMouse = 2f;

    private CinemachineFreeLook freeLookCamera;

    void Start()
    {
        // Obtener la referencia al componente CinemachineFreeLook
        freeLookCamera = GetComponent<CinemachineFreeLook>();
    }

    void Update()
    {
        float movimientoMouseX = Input.GetAxis("Mouse X");
        float movimientoMouseY = Input.GetAxis("Mouse Y");

        // Rotar la c치mara solo en el eje Y (horizontal)
        freeLookCamera.m_XAxis.Value += movimientoMouseX * sensibilidadMouse;

        // Obtener la rotaci칩n actual en el eje X (vertical)
        float rotacionActualX = freeLookCamera.m_YAxis.Value;

        // Limitar la rotaci칩n en el eje X entre -80 y 80 grados
        float nuevaRotacionX = Mathf.Clamp(rotacionActualX - movimientoMouseY * sensibilidadMouse, -80f, 80f);

        // Aplicar la rotaci칩n solo en el eje X (vertical)
        freeLookCamera.m_YAxis.Value = nuevaRotacionX;
    }
}
